<?php

namespace app\api\controller;

use app\common\controller\Api;
use app\common\helper\wechat\jwttoken;

class Wechat extends Api{

    use jwttoken;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function getOpenid(){

        $data = [
            'token'=>self::createToken(),
            'appid'=>Config('mini.appid')
        ];

        $this->success('success',$data);
    }
}
