<?php

namespace app\api\controller;

use app\common\controller\Api;
use app\common\helper\wechat\jwttoken;

class Wechat extends Api{

    use jwttoken;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $res = self::checkToken($this->allow_token);
        $this->token = $res;
    }

    public function test(){
        dump($this->token);
    }
}
