<?php

namespace app\api\controller;

use app\common\controller\Api;

class Wechat extends Api{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function test(){
        dump($this->token);
    }
}
